name: Add new issues to b´project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/genomic-medicine-sweden/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, feature request
          label-operator: OR
